version: "3"

services:

#  champion-manager-sub:
#    build:
#      context: ./building-warriors-lol-champion-sub
#      dockerfile: Dockerfile.dockerfile
#    image: champion-sub
#    networks:
#      web:
#    environment:
#      API_SERVER_PORT: 8080
#      API_DB_HOST: scylla-node1
#      API_DB_PORT: 9042
#      API_DB_KEYSPACE: lolDb
#    ports:
#      - 8080:8080
#    depends_on:
#      - scylla-node1
#      - scylla-node2
#      - scylla-node3
  
  nats:
    container_name: nats
    image: 'nats:latest'
    ports:
      - 4222:4222
    networks:
      web:
      
  database:
    container_name: lol-scylla-db
    image: scylladb/scylla:4.1.0
    command: --smp 1 --overprovisioned 1 --api-address 0.0.0.0
    ports:
      - 9042:9042
    volumes:
      - ./data/init.cql:/init.cql
      - ./data/lolDb:/var/lib/scylla
    networks:
      web:

networks:
  web:
    driver: bridge

