micronaut:
  application:
    name: buildingWarriorsLolRest
  server:
    port: ${API_SERVER_PORT:8080}

api:
  path: /api/v1

datasources:
  default:
    url: jdbc:h2:mem:${DB_NAME:lolDb}
    driverClassName: org.h2.Driver
    username: ${DB_USER:sa}
    password: ${DB_PASSWORD:''}
    dialect: H2
jpa.default.properties.hibernate:
  hbm2ddl.auto: update
  show_sql: true
endpoints:
  health:
    enabled: true