micronaut:
  application:
    name: buildingWarriorsLolRest
  server:
    port: ${API_SERVER_PORT:8080}

api:
  path: /api/v1

cassandra:
  default:
    basic:
      contact-points:
        - "127.0.0.1:9042"
      session-keyspace: loldb
      load-balancing-policy:
        local-datacenter: datacenter1


endpoints:
  health:
    enabled: true