micronaut:
  application:
    name: buildingWarriorsLolRest
  server:
    port: ${API_SERVER_PORT:8080}

api:
  path: /api/v1

cassandra:
  default:
    basic:
      contact-points:
        - ${API_DB_HOST:localhost}:${API_DB_PORT:9042}
      session-keyspace: ${API_DB_KEYSPACE}
      load-balancing-policy:
        local-datacenter: datacenter1

endpoints:
  health:
    enabled: true