micronaut:
  application:
    name: buildingWarriorsLolPub
  server:
    port: ${API_SERVER_PORT:8080}

api:
  path: /api/v1

endpoints:
  health:
    enabled: true

nats:
  addresses:
    - nats://${API_NATS_HOST:localhost}:${PORT:4222}
  username: ${API_NATS_USERNAME}
  password: ${API_NATS_PASSWORD}

